---
openapi: 3.0.1
info:
  title: Lixbox-ged
  version: "8.1.0"
  description: |
    Il s'agit d'un micro-service de ged qui repose sur des providers:
    - REDIS
    - SESIN

    ## Dépendances
    ### API
    * Nécessite un service Redis.
    * Peut s'enregistrer dans un annuaire de service lixbox-registry.

    ### UI
    * Sans objet

    ## Configuration
    ### API
    Les variables d'environnement suivantes servent à configurer le service:
    * **registry.uri**: URI du service d'annauire -> **http://main.host:18100/registry/api/1.0**
    * **redis.uri**: URI du service Redis -> **tcp://localhost:6382**
    * **quarkus.http.port**: Port exposée par le service -> **18104**
    * **storage.path**: Définitition du chemin de stockage des fichiers -> **user_home**
    * **quarkus.log.handler.gelf.enabled**: Activation du logging GRAYLOG -> **false**
    * **quarkus.log.handler.gelf.host**: Serveur GRAYLOG -> **vsrvglog.pam.lan**
    * **quarkus.log.handler.gelf.port**: Port GRAYLOG -> **12201**
    * **quarkus.jaeger.endpoint**: URI Jaeger -> **http://jaeger.service.dev.lan:14268/api/traces**

    ### UI
    sans objet 
servers:
  - url: http://localhost:18104/openapi
    description: local
paths:
  /ged/api/1.0/health:
    get:
      responses:
        "200":
          description: OK
  /ged/api/1.0/health/live:
    get:
      responses:
        "200":
          description: OK
  /ged/api/1.0/health/ready:
    get:
      responses:
        "200":
          description: OK
...
